// Generated by https://quicktype.io

export interface Freeplug {
  id: string;
  members: Member[];
}

export interface Member {
  id: string;
  tx_rate: number;
  eth_port_status: string;
  rx_rate: number;
  net_role: string;
  inactive: number;
  net_id: string;
  model: string;
  eth_speed: number;
  local: boolean;
  eth_full_duplex: boolean;
  has_network: boolean;
}

export default Freeplug;
